"""UI text labels for all supported languages."""

LABELS: dict[str, dict[str, str]] = {
    "en": {
        "font": "Arial, sans-serif",
        "invoice": "TAX INVOICE",
        "invoice_no": "Invoice No.",
        "date": "Date",
        "due_date": "Due Date",
        "bill_to": "Bill To",
        "ship_to": "Ship To",
        "vendor": "Vendor",
        "gstin": "GSTIN",
        "pan": "PAN",
        "hsn": "HSN",
        "description": "Description",
        "qty": "Qty",
        "unit": "Unit",
        "unit_price": "Unit Price (₹)",
        "amount": "Amount (₹)",
        "subtotal": "Subtotal",
        "cgst": "CGST (9%)",
        "sgst": "SGST (9%)",
        "igst": "IGST (18%)",
        "total": "Total",
        "amount_in_words": "Amount in Words",
        "bank_details": "Bank Details",
        "bank_name": "Bank Name",
        "account_no": "Account No.",
        "ifsc": "IFSC Code",
        "terms": "Terms & Conditions",
        "terms_text": "Payment due within 30 days of invoice date. Goods once sold will not be taken back.",
        "authorized_signatory": "Authorized Signatory",
        "original": "ORIGINAL",
    },
    "hi": {
        "font": "'Noto Sans Devanagari', Mangal, Arial, sans-serif",
        "invoice": "कर चालान",
        "invoice_no": "चालान संख्या",
        "date": "दिनांक",
        "due_date": "देय तिथि",
        "bill_to": "बिल प्राप्तकर्ता",
        "ship_to": "शिपिंग पता",
        "vendor": "विक्रेता",
        "gstin": "जीएसटीआईएन",
        "pan": "पैन",
        "hsn": "एचएसएन",
        "description": "विवरण",
        "qty": "मात्रा",
        "unit": "इकाई",
        "unit_price": "इकाई मूल्य (₹)",
        "amount": "राशि (₹)",
        "subtotal": "उप-योग",
        "cgst": "सीजीएसटी (9%)",
        "sgst": "एसजीएसटी (9%)",
        "igst": "आईजीएसटी (18%)",
        "total": "कुल राशि",
        "amount_in_words": "राशि शब्दों में",
        "bank_details": "बैंक विवरण",
        "bank_name": "बैंक का नाम",
        "account_no": "खाता संख्या",
        "ifsc": "आईएफएससी कोड",
        "terms": "नियम और शर्तें",
        "terms_text": "चालान दिनांक के 30 दिनों के भीतर भुगतान देय है। बेचे गए माल वापस नहीं लिए जाएंगे।",
        "authorized_signatory": "अधिकृत हस्ताक्षरकर्ता",
        "original": "मूल प्रति",
    },
    "mr": {
        "font": "'Noto Sans Devanagari', Mangal, Arial, sans-serif",
        "invoice": "कर बीजक",
        "invoice_no": "बीजक क्रमांक",
        "date": "दिनांक",
        "due_date": "देय तारीख",
        "bill_to": "बिल प्राप्तकर्ता",
        "ship_to": "शिपिंग पत्ता",
        "vendor": "विक्रेता",
        "gstin": "जीएसटीआयएन",
        "pan": "पॅन",
        "hsn": "एचएसएन",
        "description": "वर्णन",
        "qty": "प्रमाण",
        "unit": "एकक",
        "unit_price": "एकक किंमत (₹)",
        "amount": "रक्कम (₹)",
        "subtotal": "उप-एकूण",
        "cgst": "सीजीएसटी (9%)",
        "sgst": "एसजीएसटी (9%)",
        "igst": "आयजीएसटी (18%)",
        "total": "एकूण रक्कम",
        "amount_in_words": "रक्कम शब्दात",
        "bank_details": "बँक तपशील",
        "bank_name": "बँकेचे नाव",
        "account_no": "खाते क्रमांक",
        "ifsc": "आयएफएससी कोड",
        "terms": "अटी व शर्ती",
        "terms_text": "बीजक दिनांकापासून 30 दिवसांत पैसे भरणे आवश्यक आहे। विकलेला माल परत घेतला जाणार नाही।",
        "authorized_signatory": "अधिकृत स्वाक्षरीकर्ता",
        "original": "मूळ प्रत",
    },
    "kn": {
        "font": "'Noto Sans Kannada', Tunga, Arial, sans-serif",
        "invoice": "ತೆರಿಗೆ ಇನ್‌ವಾಯಿಸ್",
        "invoice_no": "ಇನ್‌ವಾಯಿಸ್ ಸಂಖ್ಯೆ",
        "date": "ದಿನಾಂಕ",
        "due_date": "ಪಾವತಿ ದಿನಾಂಕ",
        "bill_to": "ಬಿಲ್ ಸ್ವೀಕರಿಸುವವರು",
        "ship_to": "ಶಿಪ್ಪಿಂಗ್ ವಿಳಾಸ",
        "vendor": "ಮಾರಾಟಗಾರರು",
        "gstin": "ಜಿಎಸ್‌ಟಿಐಎನ್",
        "pan": "ಪ್ಯಾನ್",
        "hsn": "ಎಚ್‌ಎಸ್‌ಎನ್",
        "description": "ವಿವರಣೆ",
        "qty": "ಪ್ರಮಾಣ",
        "unit": "ಘಟಕ",
        "unit_price": "ಘಟಕ ಬೆಲೆ (₹)",
        "amount": "ಮೊತ್ತ (₹)",
        "subtotal": "ಉಪ-ಮೊತ್ತ",
        "cgst": "ಸಿಜಿಎಸ್‌ಟಿ (9%)",
        "sgst": "ಎಸ್‌ಜಿಎಸ್‌ಟಿ (9%)",
        "igst": "ಐಜಿಎಸ್‌ಟಿ (18%)",
        "total": "ಒಟ್ಟು ಮೊತ್ತ",
        "amount_in_words": "ಪದಗಳಲ್ಲಿ ಮೊತ್ತ",
        "bank_details": "ಬ್ಯಾಂಕ್ ವಿವರಗಳು",
        "bank_name": "ಬ್ಯಾಂಕ್ ಹೆಸರು",
        "account_no": "ಖಾತೆ ಸಂಖ್ಯೆ",
        "ifsc": "ಐಎಫ್‌ಎಸ್‌ಸಿ ಕೋಡ್",
        "terms": "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
        "terms_text": "ಇನ್‌ವಾಯಿಸ್ ದಿನಾಂಕದಿಂದ 30 ದಿನಗಳಲ್ಲಿ ಪಾವತಿ ಮಾಡಬೇಕು. ಮಾರಿದ ಸರಕನ್ನು ಹಿಂತಿರುಗಿಸಲಾಗದು.",
        "authorized_signatory": "ಅಧಿಕೃತ ಸಹಿಗಾರ",
        "original": "ಮೂಲ ಪ್ರತಿ",
    },
    "bn": {
        "font": "'Noto Sans Bengali', Vrinda, Arial, sans-serif",
        "invoice": "কর চালান",
        "invoice_no": "চালান নম্বর",
        "date": "তারিখ",
        "due_date": "দেয় তারিখ",
        "bill_to": "বিল প্রাপক",
        "ship_to": "শিপিং ঠিকানা",
        "vendor": "বিক্রেতা",
        "gstin": "জিএসটিআইএন",
        "pan": "প্যান",
        "hsn": "এইচএসএন",
        "description": "বিবরণ",
        "qty": "পরিমাণ",
        "unit": "একক",
        "unit_price": "একক মূল্য (₹)",
        "amount": "মোট (₹)",
        "subtotal": "উপ-মোট",
        "cgst": "সিজিএসটি (9%)",
        "sgst": "এসজিএসটি (9%)",
        "igst": "আইজিএসটি (18%)",
        "total": "মোট পরিমাণ",
        "amount_in_words": "কথায় পরিমাণ",
        "bank_details": "ব্যাংক বিবরণ",
        "bank_name": "ব্যাংকের নাম",
        "account_no": "অ্যাকাউন্ট নম্বর",
        "ifsc": "আইএফএসসি কোড",
        "terms": "শর্তাবলী",
        "terms_text": "চালানের তারিখ থেকে ৩০ দিনের মধ্যে পেমেন্ট করতে হবে। বিক্রীত পণ্য ফেরত নেওয়া হবে না।",
        "authorized_signatory": "অনুমোদিত স্বাক্ষরকারী",
        "original": "মূল কপি",
    },
    "ta": {
        "font": "'Noto Sans Tamil', Latha, Arial, sans-serif",
        "invoice": "வரி விலைப்பட்டியல்",
        "invoice_no": "விலைப்பட்டியல் எண்",
        "date": "தேதி",
        "due_date": "செலுத்த வேண்டிய தேதி",
        "bill_to": "பில் பெறுநர்",
        "ship_to": "அனுப்பும் முகவரி",
        "vendor": "விற்பனையாளர்",
        "gstin": "ஜிஎஸ்டிஐஎன்",
        "pan": "பான்",
        "hsn": "எச்எஸ்என்",
        "description": "விவரம்",
        "qty": "அளவு",
        "unit": "அலகு",
        "unit_price": "அலகு விலை (₹)",
        "amount": "தொகை (₹)",
        "subtotal": "துணை மொத்தம்",
        "cgst": "சிஜிஎஸ்டி (9%)",
        "sgst": "எஸ்ஜிஎஸ்டி (9%)",
        "igst": "ஐஜிஎஸ்டி (18%)",
        "total": "மொத்த தொகை",
        "amount_in_words": "வார்த்தைகளில் தொகை",
        "bank_details": "வங்கி விவரங்கள்",
        "bank_name": "வங்கியின் பெயர்",
        "account_no": "கணக்கு எண்",
        "ifsc": "ஐஎஃப்எஸ்சி குறியீடு",
        "terms": "விதிமுறைகள்",
        "terms_text": "விலைப்பட்டியல் தேதியிலிருந்து 30 நாட்களுக்குள் கட்டணம் செலுத்தவும். விற்கப்பட்ட பொருட்கள் திரும்பப் பெறப்படாது.",
        "authorized_signatory": "அங்கீகரிக்கப்பட்ட கையொப்பமிடுபவர்",
        "original": "அசல் நகல்",
    },
    "te": {
        "font": "'Noto Sans Telugu', Gautami, Arial, sans-serif",
        "invoice": "పన్ను ఇన్వాయిస్",
        "invoice_no": "ఇన్వాయిస్ నంబర్",
        "date": "తేదీ",
        "due_date": "చెల్లింపు తేదీ",
        "bill_to": "బిల్ స్వీకర్త",
        "ship_to": "షిప్పింగ్ చిరునామా",
        "vendor": "విక్రేత",
        "gstin": "జిఎస్టిఐఎన్",
        "pan": "పాన్",
        "hsn": "హెచ్‌ఎస్‌ఎన్",
        "description": "వివరణ",
        "qty": "పరిమాణం",
        "unit": "యూనిట్",
        "unit_price": "యూనిట్ ధర (₹)",
        "amount": "మొత్తం (₹)",
        "subtotal": "ఉప-మొత్తం",
        "cgst": "సిజిఎస్టి (9%)",
        "sgst": "ఎస్జిఎస్టి (9%)",
        "igst": "ఐజిఎస్టి (18%)",
        "total": "మొత్తం",
        "amount_in_words": "మాటలలో మొత్తం",
        "bank_details": "బ్యాంక్ వివరాలు",
        "bank_name": "బ్యాంక్ పేరు",
        "account_no": "ఖాతా నంబర్",
        "ifsc": "ఐఎఫ్ఎస్సి కోడ్",
        "terms": "నిబంధనలు",
        "terms_text": "ఇన్వాయిస్ తేదీ నుండి 30 రోజులలోపు చెల్లించాలి. అమ్మిన వస్తువులు తిరిగి తీసుకోబడవు.",
        "authorized_signatory": "అధికారిక సంతకం చేసేవారు",
        "original": "అసలు కాపీ",
    },
}
